data:
  countries:
  - austria
  - belgium
  - brazil
  - cambodia
  - corsica
  - croatia
  - denmark
  - estonia
  - finland
  - france
  - germany
  - india
  - kenya
  - latvia
  - lithuania
  - luxembourg
  - netherlands
  - portugal
  - rwanda
  - slovakia
  - slovenia
  - south_africa
  - spain
  - sweden
  - vietnam
  crop_size:
  - 256
  - 256
  in_channels: 8
  n_classes: 2
  num_samples: -1
  presence_only: true
  root_dir: /u/gmuhawenayo/datasets/FTW-Dataset/ftw
  temporal_option: stacked
experiment_description: This experiment is done for FTW 2 classes, all countries,
  2 windows. For presence_only case we are not allowing it's background to contribute
  to the loss
experiment_name: exp0910-2classes-2win
loss:
  bound_weight: 1.0
  dist_weight: 5.0
  seg_weight: 1.0
model:
  depth: 6
  ftdepth: 5
  nfilters_init: 32
  nheads_start: 4
  norm_groups: 4
  norm_type: GroupNorm
  psp_depth: 4
save_dir: ./logs-decode
train:
  batch_size: 64
  lr: 0.001
  num_epochs: 200
  num_workers: 4
  patience: 10
