trainer:
  max_epochs: 30
  log_every_n_steps: 10
  accelerator: gpu
  default_root_dir: logs/FTW-Release-Full-3-class-ViT
  devices: 
    - 0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/object_f1       
        mode: max                    
        save_top_k: 1                
        save_last: true              
        filename: "{epoch}-{val_object_f1:.4f}"
        auto_insert_metric_name: false
model:
  class_path: ftw_tools.torchgeo.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: [0.04,0.08,0.88]
    loss: "ce"                                  # options tested: 'ce' or  'dice' or 'ce+dice' or 'logcoshdice' or 'logcoshdice+ce'
    model: gfm                                  # pretrained | clay | croma | decur | dofa | dinov3 | galileo | prithvi | satlas | softcon | terrafm | terramind
    backbone: clay                              # null | clay | croma | decur | dofa | dinov3 | galileo | prithvi | satlas | softcon | terrafm | terramind
    weights: true
    patch_weights : false
    in_channels: 8
    num_classes: 3
    num_filters: 64
    ignore_index: 3
    lr: 1e-3
    patience: 100
    model_kwargs:
      fuser: mlp                                    
      decoder: conv_w_aspp                            # "conv_light" | "conv_w_aspp"
      hidden_dim: 1024
      original_input_size: 256
      patch_size: 8
data:
  class_path: ftw_tools.torchgeo.datamodules.FTWDataModule
  init_args:
    batch_size: 32
    num_workers: 16
    random_shuffle: false
    train_countries:
      - austria
      - belgium
      - brazil
      - cambodia
      - corsica
      - croatia
      - denmark
      - estonia
      - finland
      - france
      - germany
      - india
      - kenya
      - latvia
      - lithuania
      - luxembourg
      - netherlands
      - portugal
      - rwanda
      - slovakia
      - slovenia
      - south_africa
      - spain
      - sweden
      - vietnam
    val_countries:
      - austria
      - belgium
      - brazil
      - cambodia
      - corsica
      - croatia
      - denmark
      - estonia
      - finland
      - france
      - germany
      - india
      - kenya
      - latvia
      - lithuania
      - luxembourg
      - netherlands
      - portugal
      - rwanda
      - slovakia
      - slovenia
      - south_africa
      - spain
      - sweden
      - vietnam
    test_countries:
      - austria
      - belgium
      - brazil
      - cambodia
      - corsica
      - croatia
      - denmark
      - estonia
      - finland
      - france
      - germany
      - india
      - kenya
      - latvia
      - lithuania
      - luxembourg
      - netherlands
      - portugal
      - rwanda
      - slovakia
      - slovenia
      - south_africa
      - spain
      - sweden
      - vietnam
  dict_kwargs:
    root: ./data/ftw
    metadata_path: ./configs/metadata.yaml
    load_boundaries: true
    input_type: images_noaug                                       # "images" or "features" or "images_noaug"
    feat_root: null                                                #  null or "path-to-gfm-feats/precomputed_feats/clay" 
    preprocessing: clay                                            #  none or clay | croma | decur | dofa | dinov3 | galileo | prithvi | satlas | softcon | terrafm | terramind
seed_everything: 7